apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: codegen-test-oct15-gitops
  description: This is GitOps manifest for codegen-test-oct15   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: codegen-test-oct15
    janus-idp.io/tekton: codegen-test-oct15 
    backstage.io/kubernetes-id: codegen-test-oct15 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:codegen-test-oct15
