apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: codegen-test-oct15
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/jdubrick-ai/codegen-test-oct15:67ad89dbd4dbf881caf44232de09f565eb3a7d5d@sha256:912127a6ce99917da7b86b62b16328e0deef948ee108ce614c11ca7497a94b00 # use pre-built to bootstrap 
          name: app-inference
